version: "3.9"
services:
  mysql-user-service:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysqlcontainer
    networks:
      - user-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  user-authentication-service:
    container_name: user-container
    build: ./
    networks:
      - user-net
    ports:
      - "8071:8071"
    depends_on:
      - mysql-user-service
    restart: always
networks:
  user-net:
    driver: bridge